name: CI Workflow

on:
  workflow_call:
    types: [completed]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  schedule:
    - cron: '0 0 * * *' # Runs at 12:00 UTC every day

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          echo "NSW_TRANSPORT_API_KEY=${{ secrets.NSW_TRANSPORT_API_KEY }}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Build and run tests
        run: ./gradlew build

  scheduled-tasks:
    runs-on: ubuntu-latest
    needs: [setup, build]
    if: github.event_name == 'schedule'

    steps:
      - name: Download GTFS Data
        run: ./gradlew runKRAIL-GTFS

      - name: Debug - List generated files
        run: |
          if [ -d "cache" ]; then
            ls -R cache
          else
            echo "Error: cache directory does not exist"
          fi

      - name: Upload generated JSON
        id: upload-gen-stop-json-files
        uses: actions/upload-artifact@v4
        with:
          name: generated-json-files
          path: cache/NSW_STOPS.json

      - name: Create new folder for artifact
        run: mkdir -p ./nswstops

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: generated-json-files
          path: ./nswstops

      - name: Create Branch
        run: |
          timestamp=$(date +'%s')
          branch_name="nsw-gtfs-stops-${timestamp}"
          git checkout -b $branch_name
          git push origin $branch_name
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          committer: Github Actions Bot <41898282+github-actions[bot]@users.noreply.github.com>
          author: Github Actions Bot <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: 'Add generated NSW_STOPS.json'
          title: 'Add generated NSW_STOPS.json'
          body: |
            ### Description
            Automated PR to add GTFS Stops as a JSON files.