name: Run Project and Create PR

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 2 * *' # Runs at 00:00 on the 2nd of every month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew build

      - name: Run the project
        run: ./gradlew run

      - name: Get current date and time
        id: date
        run: echo "DATE=$(date +'%d%b_%H%M')" >> $GITHUB_ENV

      - name: Create Pull Request with NSW_STOPS.json
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Add generated NSW_STOPS.json'
          branch: 'generated-json'
          title: 'Add generated NSW_STOPS.json - ${{ env.DATE }}'
          body: 'This PR adds the generated NSW_STOPS.json file.'
          labels: 'autogenerated'
          path: 'cache/NSW_STOPS.json'