name: Schedule a workflow

on:
  schedule:
    - cron: '30 11 * * *' # Runs at 11:30 UTC every day (21:30 AEST)

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yml
    with:
    # Add any inputs if needed
    secrets: inherit